name: base
channels:
  - conda-forge
dependencies:
  - nbsphinx
  - nbsphinx-link
  - pydata-sphinx-theme
  - sphinx-copybutton
  - sphinx-favicon
  - sphinx-thebe
  - sphinx-togglebutton
  - pandoc
  - numpy
  - sphinxawesome-theme
